// Courses actions
export const COURSES_ACTIONS = {
  ALL: 'COURSES_ALL',
  BY_ID: 'COURSES_BY_ID',
  LOADING: 'COURSES_LOADING',
  FAILED: 'COURSES_FAILED',
};

// User actions
export const USER_ACTIONS = {
  SIGN_IN: 'SIGN_IN',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_OUT: 'SIGN_OUT',
  LOADING: 'USER_LOADING',
};
